### ISSUE TITLE
Support for Basic Auth

### ISSUE THREAD

**Issue by weaverryan** [minkphp/MinkSelenium2Driver#11]
Hey guys!

I noticed that none of the JS drivers (Selenium, Selenium2, Sahi) support basic authentication. Is this inherently not supported by those underlying tools or has it just not been implemented yet inside the drivers?

Thanks!

**Comment by pscheit** [comment]
is this still the case in 2019?
It would be SO helpful to have http basic auth /other hacks for a huge acceptance testsuites
