### ISSUE TITLE
Internet Explorer Crash Since Selenium 2.43

### ISSUE THREAD

**Issue by MajorOutage** [minkphp/MinkSelenium2Driver#186]
Hi guys,

it appears to me like there is a problem when trying to connect with a selenium version higher or even version 2.43. Following setup ("selenium version" always refers to the standalone server and the Internet Explorer Driver version):
- connecting to a selenium node on Win7 and IE10 (but the same error appears on WinXP and IE6)
- normal behaviour when using selenium version 2.42 and lower
- error "Command line server for the IE driver has stopped working" when using 2.43 and higher
- no problem when testing firefox

As the service crashes immediately the following within a .feature-file is sufficient to reproduce:

```
@javascript
    Scenario: Searching for a page with autocompletion
    Given I am on "/wiki/Main_Page"
```
- [composer-setup](https://gist.github.com/MajorOutage/7055573ee0acc96b6d67#file-composer_setup)
- the [log file](https://gist.github.com/MajorOutage/7055573ee0acc96b6d67#file-selenium_node_log) from the selenium node
- [behat.yml](https://gist.github.com/MajorOutage/7055573ee0acc96b6d67#file-behat-yml) (only the two ie-sections are relevant)

I don't know about the internals, but when I was playing around with some settings I commented out the line `->scalarNode('ignoreZoomSetting')->defaultValue('false')->end()` in the file `src/Behat/MinkExtension/ServiceContainer/Driver/Selenium2Factory.php`, which solved the problem. Maybe this helps narrowing done the cause.

**Comment by stof** [comment]
Closing as this looks like a selenium bug if selenium stops running.
