### ISSUE TITLE
Selenium2 driver - exception when retrieving an attribute

### ISSUE THREAD

**Issue by mikolaj-ifr** [minkphp/MinkSelenium2Driver#200]
1/ Implementation

The second line of the following code throws an error:

```php
$element = $this->getSession()->getPage()->find('css', 'input[type="email"]');
$element->getAttribute('class');
```

2/ Logs

- Behat:
```
Curl error thrown for http POST to http://localhost:4444/wd/hub/session/c956a70d-0fe1-4166-85dd-2f7250886c47/execute with params: {"script":"return arguments[0].getAttribute(\"class\")","args":[{"ELEMENT":"0"}]}
The requested URL returned error: 500 Internal Server Error (WebDriver\Exception\CurlExec)
```

- Selenium server: 
```
WARN - Exception thrown org.openqa.selenium.WebDriverException: arguments[0] is undefined
```

3/ Configuration

- Behat:
```
behat/mink                        dev-master 1125c2f Browser controller/emulator abstraction for PHP
behat/mink-browserkit-driver      dev-master 2a7a727 Symfony2 BrowserKit driver for Mink framework
behat/mink-extension              dev-master ba5329b Mink extension for Behat
behat/mink-goutte-driver          dev-master 63a593c Goutte driver for Mink framework
behat/mink-selenium2-driver       dev-master ce4766a Selenium2 (WebDriver) driver for Mink framework
```

- Selenium server: 2.44

**Comment by mikolaj-ifr** [comment]
Issue does not exist with the following Behat/Mink version:

behat/mink                   v1.5.0 Web acceptance testing framework for PHP 5.3
behat/mink-browserkit-driver v1.1.0 Symfony2 BrowserKit driver for Mink framework
behat/mink-extension         v1.3.3 Mink extension for Behat
behat/mink-goutte-driver     v1.0.9 Goutte driver for Mink framework
behat/mink-selenium2-driver  v1.1.1 Selenium2 (WebDriver) driver for Mink framework

**Comment by aik099** [comment]
Please use fenced code blocks. I wonder if anybody does read GitHub usage manual at all, because 9 of 10 tickets submitted don't use fenced code blocks, which makes it hard to read the code.

**Comment by aik099** [comment]
> `$element = $this->getSession()->getPage()->find('css', 'input[type="email"]');`

1. Does this line find an element?
2. What if you change selector to work by ID and not CSS, would attribute retrieval work then?

**Comment by mikolaj-ifr** [comment]
- Yes the element is find with the css selector
- The same issue occurs when retreiving the element with the named selector:

'''
$element = $this->getSession()->getPage()->findById('email');
''''

**Comment by stof** [comment]
The issue is probably that you are using Firefox 35, and Selenium 2.44 is not compatible with it. See https://github.com/minkphp/MinkSelenium2Driver/issues/198#issuecomment-75028897

**Comment by stof** [comment]
Btw, the versions of Mink and of drivers you are using are totally outdated. 1.5.0 is nearly 2 years old.

**Comment by mikolaj-ifr** [comment]
No, thoose versions are for the case when the error does not occur (second comment).

**Comment by mikolaj-ifr** [comment]
The issue was indeed related to firefox 35. 
Version 34 works fine.

Thank you.

**Comment by aik099** [comment]
@stof , we should post a banner in README.md, that `Selenium Server 2.44- and Firefox 35 = JS don't work`.
