### ISSUE TITLE
Allow setValue function to not ensure unfocus an input field

### ISSUE THREAD

**Issue by jdecool** [minkphp/MinkSelenium2Driver#208]
I use mink to interact with some javascript managed fields (with select2 jquery plugin for example).

I recently upgrade Behat 2.X to 3.X on a project. But some features are broken because of the `setValue` function :
```php
 if (in_array($elementName, array('input', 'textarea'))) {
     $existingValueLength = strlen($element->attribute('value'));
     // Add the TAB key to ensure we unfocus the field as browsers are triggering the change event only
     // after leaving the field.
     $value = str_repeat(Key::BACKSPACE . Key::DELETE, $existingValueLength) . $value . Key::TAB;
}
```
I use Mink to open the select field, search for a value and pick up one in the result. But the driver force a tabulation key press and the search is canceled.

Is it possible to change how the function working and allow user to not enforce unfocus when he set a field value ?

I look at the SahiDriver to make a comparison and this behaviour is not consistent with others drivers.

**Comment by aik099** [comment]
Please see following issues for more information:

* #188
* #194
* #198

**Comment by jdecool** [comment]
Thanks for your answer. I close this issue PR because of duplication.

**Comment by aik099** [comment]
@jdecool , if you have any fixing ideas for that problem, then please post in tasks I've mentioned.

**Comment by jdecool** [comment]
Ok. For now I use the work around explain in #188
