### ISSUE TITLE
[maybe] Add a note about not working with Chrome >43

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkSelenium2Driver#214]
Maybe we should add a note in README.md, that input filling doesn't work properly with Google Chrome above 43 version (see #213).

**Comment by kleijnweb** [comment]
+1

I just spent 3 hours figuring this out.

**Comment by taraneier** [comment]
Could this have anything to do with "screen-resolution" capabilties not being honored with chrome browsers?

**Comment by aik099** [comment]
@taraneier , I think this is not related. Please see my answer at #237.

**Comment by aik099** [comment]
Current Chrome version is 51 and new Selenium was also released. Probably this is no longer an issue.

**Comment by dsnopek** [comment]
Yeah, underlying Chrome bug got fixed:

https://bugs.chromium.org/p/chromium/issues/detail?id=513768
