### ISSUE TITLE
Implementation of setFileDetector

### ISSUE THREAD

**Issue by generalconsensus** [minkphp/MinkSelenium2Driver#224]
I wanted to bring up the possibility of adding the setFileDetector functionality (https://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/remote/RemoteWebDriver.html#setFileDetector(org.openqa.selenium.remote.FileDetector) for use with Mink. 

With this implemented, remote tests on SAAS drivers through Selenium 2 will allow local files to be sent base64 so that local files will be available in remote SAAS tests

Here are two references for Sauce Labs and for Browserstack:

https://saucelabs.com/resources/articles/selenium-file-upload

https://www.browserstack.com/automate/php

**Comment by aik099** [comment]
We're using https://github.com/instaclick/php-webdriver for communition with Selenium server and it doesn't seem to supported.

In the #187 discussion we're investigating possibilities of remote file uploads as well.

**Comment by stof** [comment]
Should be fixed by #252 AFAIK.
