### ISSUE TITLE
Add setter for xpathEscaper

### ISSUE THREAD

**Issue by funivan** [minkphp/MinkSelenium2Driver#236]
It would be great to set xpathEscaper via setter. I cant modify if I extend Seleium2Driver

**Comment by aik099** [comment]
Why you need to use different xpath escaper. The xpath syntax doesn't change that much (or at all 😄 ).

**Comment by funivan** [comment]
It is easy to show code: https://gist.github.com/funivan/127153ac920e0f7e0509b7e4b7865db6
I do not have url for webdrive on class initialization. I detect port on driver start and then I can init webdrive. 
My current example working fine but I do not need to init Webdrive. Inside constructor I want to write following code 
```php
/**
     * @inheritDoc
     */
    public function __construct(PhantomJsServer $phantomJsServer, $desiredCapabilities = null) {
       $this->phantomJsServer = $phantomJsServer;

        $this->setBrowserName('firefox');
        $this->setDesiredCapabilities($desiredCapabilities);
        $this->setXpathEscaper(new Escaper()); // here is the failure.

    }
```

If this is hard to do then you can close this issue. But to make selenium2Driver more extensible it will be cool to add setter for xpathEscaper.

**Comment by aik099** [comment]
Not sure if you know, but there is official Mink driver for PhantomJS (not through WebDriver protocol).

And I'm still not sure why you need delayed WebDriver construction.

**Comment by stof** [comment]
The question still remains. Why do you want to change the XPathEscaper from the outside ?

If your goal is to be able to skip calling the parent constructor, this is not an acceptable reason. not calling the parent constructor means that your class is in a broken state (missing initialization of the class). And even if you try to replicate this logic, it will be very fragile, as we can change the internal logic of the constructor at any time (even in patch releases). So this won't be accepted.
IMO, the actual extension point you are missing is *not* the one allowing to change the XPathEscaper IMO.

> but there is official Mink driver for PhantomJS (not through WebDriver protocol).

not an official one. but there is a community-maintained one.

See https://github.com/minkphp/Mink/issues/654 for a discussion about it.

**Comment by funivan** [comment]
> The question still remains. Why do you want to change the XPathEscaper from the outside ?
I just need to initialize class properly. But now, I will call parent constructor.
Thanks for help.

p.s. It will be cool to have PhantomJs as official mink driver
