### ISSUE TITLE
[Improvement] Adding the function executeScriptAndReturn()

### ISSUE THREAD

**Issue by mohsenny** [minkphp/MinkSelenium2Driver#242]
Hey guys,

Is it OK to add the function `executeScriptAndReturn()`, the same way that `executeScript()` works, with the only difference of a return statement at the end to return the result of the script execution? 
I have tested it locally already and it works fine. I thought maybe mention it here first and then create a pull request.
Two pull requests would be necessary: One in this repo, and the other one in `minkphp/Mink`

Thank you

**Comment by mohsenny** [comment]
@stof Thanks for your time

**Comment by aik099** [comment]
The `executeScript` executes the script, but the `evaluateScript` executes script and returns the result. Are you sure you need another function?

**Comment by mohsenny** [comment]
I think another function that executes the scripts AND return the result would be nice. By returning the result I do not mean just true or false indicating if the execution was successful or not, but more like the actual returning value. In my current situation something like:

```
$snippet = <<<JS
        return (
            window.getComputedStyle(document.getElementById('$id'), null).getPropertyValue('$attr')
        );
JS;

$result = $this->getSession()->executeScriptAndReturn($snippet);
```
`$result` will contain some css value

**Comment by mohsenny** [comment]
It does! the part `evaluate` in the function name kinda mislead me. I thought it only evaluates the script and returns `true`/`false` to show if it's executable or not. Thank you so much for your answer.

**Comment by stof** [comment]
it evaluates a JS expression, and returns the result of the evaluation

**Comment by mohsenny** [comment]
yep, my bad. Later on I realized the functionality is already included. Thank a lot!
