### ISSUE TITLE
Any plans to switch to Selenium 3?

### ISSUE THREAD

**Issue by seggen-ibuildings** [minkphp/MinkSelenium2Driver#250]
BrowserStack says I have to use Selenium 3 if I want to test Firefox 48 and above. If I'm not mistaken, Mink Selenium2 Driver uses instaclick/php-webdriver, which supports Selenium 2 exclusively.

Are there any plans for supporting Selenium 3? Are there ways to use Selenium 3 now?

**Comment by aik099** [comment]
Does public API of Selenium3 changes compared to Selenium2?

**Comment by stof** [comment]
I have not yet tested the driver on Selenium3. but their announcement says that the WebDriver API has no BC break between Selenium 2 and 3, so it should work fine

**Comment by stof** [comment]
Note however, that Selenium 3 requires you to have GeckoDriver in your PATH to use firefox (similar to what was already necessary in Selenium 2 for IE and Chrome), instead of having a builting driver for Firefox (there is still a legacy FirefoxDriver, but it does not support Firefox 48 and higher).

**Comment by seggen-ibuildings** [comment]
Sounds cool, thanks. So this might turn into a config option in the near future?

I'm beginning to get the feeling, however, that BrowserStack is not asking me to switch to Selenium 3, but rather, is saying I should run version 3 myself, because they don't. 🤔

**Comment by stof** [comment]
which config option ? Mink itself is not running Selenium. It connects to a running Selenium server.

In the case of BrowserStack, Selenium is running on the BrowserStack servers.

**Comment by pfrenssen** [comment]
I'm already using Selenium 3 and it works fine without any change needed. I'm having some trouble with Firefox, but that is because they are still finalizing their driver for Selenium 3.

**Comment by aik099** [comment]
Nice. Closing then.

**Comment by seggen-ibuildings** [comment]
Thanks guys.

So I guess the summary is: there's no need to change anything in your configuration. Just install Selenium 3 instead of Selenium 2 and you are good to go. Am I right?

**Comment by stof** [comment]
@seggen-ibuildings yes

**Comment by seggen-ibuildings** [comment]
For posterity sake, I tried it, and it works, but there are still some problems.

If you want BrowserStack to spin up Selenium 3, you should add `'browserstack.selenium_version': '3.0.1'` to `extra_capabilities`. This means you can run your tests in Firefox 48+ using Marionette, but I ran into a bug as soon as I tried to click an element: "moveto did not match a known command".

This bug is known, but it seems the people at Mozilla are waiting for the W3C WebDriver specification to settle :( See: https://github.com/SeleniumHQ/selenium/issues/2285
