### ISSUE TITLE
Consider dropping PhantomJS from the Travis matrix

### ISSUE THREAD

**Issue by stof** [minkphp/MinkSelenium2Driver#258]
the PhantomJS webdriver implementation has not made much progress in years AFAICT, as [GhostDriver](https://github.com/detro/ghostdriver) (the project writing this implementation) does not have an active maintainer anymore, and PhantomJS has not brought an update of ghostDriver since years (last sync was 4 years ago, for GhostDriver 1.0.0, meaning that improvements done in the meantime are unavailable when using ``phantomjs --webdriver``).

So I suggest dropping it from our test matrix.

**Comment by stof** [comment]
Thus, for people wanting to use PhantomJS to run tests to avoid the need for xvfb on CI servers, there is a now a community driver using it directly and with a much better support of the Mink Driver API.

**Comment by aik099** [comment]
Ageed. Just to be sure people are aware of this PhantomJS driver I recommend advertising it on this driver README.md.

**Comment by stof** [comment]
> on this driver README.md.

We never advocated ``phantomjs --webdriver`` in the readme. and in the doc, we say we run tests against it but they never passed. So I think it is not necessary

There is a WIP about linking to the PhantomJS driver in the doc though

**Comment by stof** [comment]
refs #132

**Comment by stof** [comment]
Btw, the main reason I have to vote here is that PhantomJS itself seems to have abandonned it (no update of the GhostDriver code to their last release, and even less to the unreleased community fixes of the past few years)

**Comment by pfrenssen** [comment]
PhantomJS development has been officially halted, and the project was archived. I agree we should not continue running tests on it.

Ref. https://github.com/ariya/phantomjs/issues/15344

**Comment by aik099** [comment]
What is the alternative?

**Comment by stof** [comment]
wrell, phantomJS was already an alternative here. It is not the main webdriver implementation.
