### ISSUE TITLE
Does Behat Mink UI test with Selenium support testing for hybridauth? 

### ISSUE THREAD

**Issue by engharb** [minkphp/MinkSelenium2Driver#266]
Hi,
Is there a Behat Mink UI test with Selenium for hybridauth [[https://github.com/hybridauth/hybridauth](https://github.com/hybridauth/hybridauth)]? I need to write a Behat test for my social login
process, where I can insert my test social account credential and get a response....

regards,

**Comment by aik099** [comment]
This is Mink Driver only. There are no sample tests to start with. I guess you need to write your own using existing methods of `MinkFeatureContext`.
