### ISSUE TITLE
better error reporting needed

### ISSUE THREAD

**Issue by individual-it** [minkphp/MinkSelenium2Driver#267]
I'm running tests with Mink on Saucelabs (Sauce Connect 4.4.6)
After updating mink-selenium2-driver from 1.3.1 to devmaster tests with firefox started to fail with 
`Expected to be on "http://localhost/owncloud-core/index.php/login" but found "" instead (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException)`

It took me a while and some network sniffing to find out that the Error Message send from Sauce Connect actually is:
`The requested combination of browser, version and OS is unsupported by the requested Selenium version and would lead to a test failure. Please set a different Selenium version, or set none to get the default, working Selenium version for this platform: firefox 47.0. on Windows 2008 with Selenium 2.31.0`

I had to set the selenium version. No idea why it did work automatically before. But a better error reporting on the console or log file would be good

**Comment by aik099** [comment]
Probably the test failure (the `UnexpectedPageException`) has previous exception set to the error you wanted to see. What was wrong here is part that showed the error back to user (not sure if it's a driver-specific code or mink shared code) wasn't showing nested/previous exceptions.

**Comment by stof** [comment]
this UnexpectedPageException is not coming from Mink, but from SensioLabs\Behat\PageObjectExtension, which is something we don't control. You should report things there to make them display more details if they have them

**Comment by individual-it** [comment]
Opened an issues in the GitHub repo of SensioLabs\Behat\PageObjectExtension. Closing this?

**Comment by aik099** [comment]
Yes, closing.
