### ISSUE TITLE
New version release?

### ISSUE THREAD

**Issue by JordiGiros** [minkphp/MinkSelenium2Driver#284]
30 commits to master branch since 1.3.1 release...
Will it be a new version release someday?

**Comment by aik099** [comment]
Sure, once all tests pass. Doesn't look like that state is met now.

**Comment by JordiGiros** [comment]
I was asking because it's been more than two years since last release.
Thank you.

**Comment by aik099** [comment]
If only more people were involved in PR sending that would fix the driver to work. You can help by fixing any of the issues causing build to fail.

**Comment by aik099** [comment]
After #303 was merged could you (@oleg-andreyev) please prepare a new release:

1. send PR with a changelog since last release
2. decide what is the new release version (based on presense of BC breaks); 

Is PHP 5.3 dropping isn't a BC break?
