### ISSUE TITLE
Fixing the Build

### ISSUE THREAD

**Issue by aik099** [minkphp/MinkSelenium2Driver#287]
All of recent builds are failing due different reasons.

- The PHP 5.3 build fails due incorrect Ubuntu version usage (no PHP 5.3 available on it)
- The PHP 5.x builds fail due Fatal Error (because Selenium 2 doesn't work on latest Firefox provided by Travis CI)
- The PHP 7.x builds fail (almost all tests failed) due timeout issues connecting to Selenium Server (have no idea why)
- The PHP 7.x build using remote virtual machine for running selenium works, but have 2 tests failed

**Comment by aik099** [comment]
Currently I'm stuck on https://github.com/minkphp/driver-testsuite/issues/21, when attempting to run tests locally.

**Comment by jibran** [comment]
> Selenium 2 doesn't work on latest Firefox provided by Travis CI

I think this can be fixed by https://github.com/instaclick/php-webdriver/commit/be87042314cc654f7ff3e26c20a998cadb23daac. PR for updating the library is https://github.com/minkphp/MinkSelenium2Driver/pull/289 but the larger discussion is https://github.com/minkphp/MinkSelenium2Driver/issues/254 which is of course block on this. :slightly_smiling_face:

**Comment by aik099** [comment]
Maybe. I was able to get test suite working (at least not a fatal error) on PHP 5.5 locally using Chrome. I've attempted to get same effect on Travis CI using #290, but it's not working. Attempt to debug the build also failed with `access denied` error.

**Comment by greg0ire** [comment]
How about just dropping php 5 support, if fixing php 5 builds is all that is left to do?

**Comment by aik099** [comment]
@greg0ire , there are multiple similar issues. There are also PRs created, that use Facebook Driver instead of InstaClick, that also require PHP 7 at least.

**Comment by greg0ire** [comment]
Similar issues about dropping php 5? Or something else? I can create a PR to drop php 5 if you want me to, I think doing so in a minor release would not be an issue since php 5 is EOL'ed: https://www.php.net/supported-versions.php

**Comment by aik099** [comment]
Issues/PRs are about switching to different WebDriver implementation. It just happens, that different WebDriver implementation require PHP 7 at minimum and that would in turn force to increase minimal supported version for this repository as well.

**Comment by greg0ire** [comment]
I think php 5 could be dropped regardless of what happens on other repositories, and in fact, maybe it could be dropped on all repositories, thus enabling easier decision-making and maintenance. This is probably not the right place to discuss it, but maybe you could consider it?

**Comment by aik099** [comment]
Currently supporting PHP 5 for Mink repositories doesn't create any additional challenges. If cross-dependency issues (e.g. supporting Symfony 4) arise, then they're solved pretty quickly.

**Comment by greg0ire** [comment]
Hasn't Mink been incompatible with sf/css-selector 4 for quite a long time now?

**Comment by rpkamp** [comment]
> Currently supporting PHP 5 for Mink repositories doesn't create any additional challenges.

Maybe not, but if it were dropped:

- we could have `strict_types`
- we could have scalar type hints
- we could have return types
- `array()` could be replaced with `[]`
- Travis would be faster, because it has to run less tests

Just to name a few.

PHP 5 has been EOL for half a year now. If PHP itself doesn't support it anymore, why should Mink?

**Comment by RuslanZavacky** [comment]
You might also want to look at it from another side - PHP 5 doesn't get any security invulnerabilities. Supporting any package after such period, contributes to the bad actors intentions and not the community.
