### ISSUE TITLE
Changes in master have broken Drupal's test suite

### ISSUE THREAD

**Issue by alexpott** [minkphp/MinkSelenium2Driver#324]
#322 and #323 have broken Drupal's Javascript testing. If I use the master branch of the driver unless I revert these two changes tests that used to pass now fail.

**Comment by alexpott** [comment]
#322 is breaking because it looks like we're not quite waiting enough for things to be interactive.

**Comment by alexpott** [comment]
#323 is breaking because we are passing the following to condition.
```
    $condition = <<<JS
      (function() {
        function isAjaxing(instance) {
          return instance && instance.ajaxing === true;
        }
        return (
          // Assert no AJAX request is running (via jQuery or Drupal) and no
          // animation is running.
          (typeof jQuery === 'undefined' || (jQuery.active === 0 && jQuery(':animated').length === 0)) &&
          (typeof Drupal === 'undefined' || typeof Drupal.ajax === 'undefined' || !Drupal.ajax.instances.some(isAjaxing))
        );
      }());
JS;
```
Which used to work prior to #323

**Comment by alexpott** [comment]
I think it could be argued that both fixes could be done in Drupal, however say the next release is 1.41 and that contains the PHP 8 fix #320 I'm not sure a bugfix release should contain them.

**Comment by alexpott** [comment]
Here's what it would take to make Drupal's tests pass on master - https://www.drupal.org/project/drupal/issues/3174928

**Comment by stof** [comment]
I think adding a `rtrim($condition, ';')` in `wait()` might fix that case.

**Comment by stof** [comment]
@alexpott do you want to send a PR for this fix ?

Note that I still suggest to land the Drupal patch though, as the argument is meant to be an expression and so the `;` should not be included in it.

**Comment by stof** [comment]
Closing this as the BC break of #323 has been solved, and the timeout issue has been solved on Drupal (to stop implicitly relying on the fact that `->waitFor()` was waiting long by default and so replacing an explicit wait necessary before the first check in case the JS needed time to react to the button click)
