### ISSUE TITLE
Add support for webdriver's Print Page

### ISSUE THREAD

**Issue by marianomd** [minkphp/MinkSelenium2Driver#335]
It would be great if we could print the page to PDF.

[php-webdriver has just implemented it](https://github.com/instaclick/php-webdriver/blob/master/lib/WebDriver/Session.php)

**Comment by aik099** [comment]
How this could help in UI testing, which is the primary use case of Mink?

**Comment by stof** [comment]
Also, this is not something that fits in the Mink driver abstraction. So if you want to use that, you should access the Webdriver layer directly.

**Comment by marianomd** [comment]
@aik099 I'm not using it for the primary use case. Mink is a great tool for general browser automation too.
@stof Thanks, I'll dig into that.

**Comment by aik099** [comment]
@marianomd , I don't recall exact method names, but code similar to this should work:

```php
$session->getDriver()->getWdSession()->print();
```
