### ISSUE TITLE
evaluateScript function returns NULL

### ISSUE THREAD

**Issue by exu** [minkphp/MinkSelenium2Driver#61]
I have problem (I think that you can help me with that if this is bug in Selenium Driver)
I try to evaluate some javascript variable but Selenium driver returns null on each try.
Example below is from Listener but i have the same results in Context classes. 

```
        $result = $event->getContext()
              ->getSession()
              ->evaluateScript("(function(){ return '11111'; })()");
```

I've tried to run closure (like above), and simply return variable

```
        $result = $event->getContext()
              ->getSession()
              ->evaluateScript("document.location.href");
```

One workaround I've found is to write variable contents to some tag / data attribute and pull those data to PHP script from there (getAttribute from NodeElement).

**Comment by Lewik** [comment]
For me for multistatement js I need to use that:
```
echo $session->evaluateScript(
    "return (function(){ doSmthElse(); return 'something from browser'; })()"
);
```
